---
- hosts: prometheus
  remote_user: dannyseeless
  become: true
  tasks:
  - name: Install Docker repository
    yum_repository: 
      name: Docker-CE-Stable
      description: Docker CE Stable - $basearch
      baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
      enabled: yes 
      gpgcheck: yes 
      gpgkey: https://download.docker.com/linux/centos/gpg 
  - name: Install Docker
    yum:
      name: docker-ce
      state: latest
    notify:
      - restart docker
  - name: Install docker-py module for docker_container ansible module
    yum: 
      name: python-docker-py
      state: latest
  - name: flush handlers to get Docker restarted
    meta: flush_handlers
  - name: Copy prometheus config
    copy:
      src: config/prometheus/
      dest: /var/lib/docker/volumes/prometheus/_data/
    notify: restart prometheus
  - name: Copy alertmanager config
    copy:
      src: config/alertmanager/
      dest: /var/lib/docker/volumes/alertmanager/_data/
    notify: restart alertmanager
  - name: Spin up the prometheus container
    docker_container:
      name: prometheus
      image: quay.io/prometheus/prometheus:v2.2.1
      state: started
      network_mode: host
      command: --config.file=/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --web.console.libraries=/usr/share/prometheus/console_libraries --web.console.templates=/usr/share/prometheus/consoles
      published_ports:
        - 9090:9090
      volumes:
        - "prometheus:/prometheus"
  - name: Spin up prometheus node exporter on prometheus host
    docker_container:
      name: node-exporter
      image: quay.io/prometheus/node-exporter:v0.15.2
      pid_mode: host
      network_mode: host
      state: started
  - name: Spin up alertmanagers on prometheus hosts
    docker_container:
      name: alertmanager
      image: quay.io/prometheus/alertmanager:v0.14.0
      network_mode: host
      command: --config.file=/alertmanager/alertmanager.yml --storage.path=/alertmanager
      state: started
      published_ports:
        - 9093:9093
      volumes:
        - "alertmanager:/alertmanager"

  handlers:
    - name: restart docker
      service: name=docker state=restarted enabled=yes
    - name: restart prometheus
      docker_container: name=prometheus state=started restart=yes
    - name: restart alertmanager
      docker_container: name=alertmanager state=started restart=yes

