global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']

rule_files:
- 'alerting.rules'
alerting:
  alertmanagers:
  - static_configs:
    # Ideally, these targets should all point to hostnames
    - targets:
      - localhost:9093

