# The directory from which notification templates are read.
templates: 
- '/etc/alertmanager/template/*.tmpl'

route:
  group_by: [Alertname]
  # Send all notifications to me.
  receiver: email-me

receivers:
- name: email-me
  email_configs:
  - to: $EMAIL_ADDR
    from: $FROM_EMAIL_ADD
    smarthost: $SMTP_SERVER_WITH_PORT
    auth_username: 
    auth_identity:
    auth_password:

